export interface NavItem {
  label: string
  href: string
}

export interface PermissionNode {
  node: string
  label: string
  description: string
}

export const PERMISSION_NODES: PermissionNode[] = [
  { node: 'query_brain', label: 'Query the Brain', description: 'Ask questions and use all read tools (search memory, Gmail, Drive).' },
  { node: 'capture_memory', label: 'Capture Memory', description: 'Submit "Remember this" proposals and use memory write tools (propose_memory, Drive write).' },
  { node: 'send_email', label: 'Send Email', description: 'Send emails via connected Gmail account.' },
  { node: 'review_queue', label: 'Review Proposal Queue', description: 'Approve or reject memory proposals in the ingestion review queue.' },
  { node: 'manage_connectors', label: 'Manage Connectors', description: 'Connect/disconnect integrations and configure exclusion rules.' },
  { node: 'manage_routines', label: 'Manage Routines', description: 'Create, edit, and enable/disable proactive routines.' },
  { node: 'manage_users', label: 'Manage Users', description: 'Invite, deactivate, and assign roles to users.' },
  { node: 'manage_roles', label: 'Manage Roles', description: 'Create and edit role definitions.' },
  { node: 'manage_system_config', label: 'Edit System Settings', description: 'Change global system configuration including retrieval thresholds and decay settings.' },
  { node: 'approve_suggestions', label: 'Approve AI Suggestions', description: 'Approve or reject self-improvement suggestions generated by the weekly analysis cron.' },
  { node: 'edit_memory', label: 'Edit & Invalidate Memories', description: 'Directly edit, invalidate, or broaden sensitivity on memory records.' },
]

// PRD §12.12 — Navigation and Default Views by Role.
// Each role sees exactly these items. Higher roles include lower-role items.
const MEMBER_NAV: NavItem[] = [
  { label: 'Query', href: '/' },
  { label: 'Memory Inspector', href: '/memory' },
]

const MANAGER_NAV: NavItem[] = [
  ...MEMBER_NAV,
  { label: 'Agent Activity', href: '/activity' },
]

const OPERATOR_NAV: NavItem[] = [
  ...MANAGER_NAV,
  { label: 'Ingestion & Queue', href: '/ingestion' },
  { label: 'Proactive Builder', href: '/proactive' },
  { label: 'Connector Management', href: '/connectors' },
]

const OWNER_NAV: NavItem[] = [
  ...OPERATOR_NAV,
  { label: 'Self-Improvement', href: '/improvement' },
  { label: 'Cost Monitor', href: '/cost' },
  { label: 'Quality Monitor', href: '/quality' },
  { label: 'System Health', href: '/health' },
  { label: 'Audit Log', href: '/audit' },
  { label: 'Mission Control', href: '/mission-control' },
]

export const ROLE_NAV_ITEMS: Record<string, NavItem[]> = {
  Member: MEMBER_NAV,
  Manager: MANAGER_NAV,
  Operator: OPERATOR_NAV,
  Owner: OWNER_NAV,
  Admin: OWNER_NAV,
}

export function getNavItems(roleName: string): NavItem[] {
  return ROLE_NAV_ITEMS[roleName] ?? MEMBER_NAV
}

export function hasRouteAccess(roleName: string, pathname: string): boolean {
  const items = getNavItems(roleName)
  if (pathname === '/') return true
  return items.some((item) => pathname.startsWith(item.href) && item.href !== '/')
}
